config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, only: [:index, :show, :new, :create, :edit, :update] do
    resources :reviews, only: [:create]
  end
  resources :reviews, only: [:destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # get "/restaurants", to: "restaurants#index"
  # get "/restaurants/new", to: "restaurants#new"
  # post "/restaurants", to: "restaurants#create"
  # get "/restaurants/:id", to: "restaurants#show", as: 'show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :address, :category, :phone_number, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
   validates :content, :rating, :restaurant_id, presence: true
   validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(resto_params)
    if @restaurant.save
    redirect_to @restaurant
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new(restaurant_id: @restaurant.id)
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(resto_params)
    redirect_to @restaurant
  end

private

  def resto_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_restaurant, only: %i[new create]
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
      @review.restaurant = @restaurant
      if @review.save
        redirect_to @restaurant
      else
        render "restaurants/show", status: :unprocessable_entity
      end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color: #e3f2fd;">
      <div class="container-fluid">
        <%= link_to "YelpClone", restaurants_path, class: "navbar-brand active" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to "Home", restaurants_path, class: "nav-link active" %>
            <%= link_to "New Restaurant", new_restaurant_path, class: "nav-link active" %>
          </div>
        </div>
      </div>
    </nav>
    <div class="container mt-5">
    <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h2>Edit Restaurant</h2>
  <%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, :collection => %w[chinese italian japanese french belgian] %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<div class="header d-flex justify-content-between align-items-center">
  <div class="title">
    <h1 class="mb-3">Restaurants</h1>
  </div>
  <div>
    <%= link_to "Add a new restaurant", new_restaurant_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="restaurant-cards">
<% @restaurants.each do |restaurant| %>
  <div class="card restaurant-card h-100">
    <div class="card-body d-flex flex-column">
      <h5 class="card-title"><%= restaurant.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= restaurant.category.capitalize %></h6>
      <p class="card-text flex-grow-1"><%= restaurant.address %></p>
      <p class="card-text"><%= restaurant.phone_number %></p>
      <div class="mt-auto">
        <%= link_to "See details", restaurant_path(restaurant), class: "card-link" %>
        <%# <%= link_to "Add review", new_restaurant_review_path(restaurant), class: "card-link" %>
      </div>
    </div>
</div>
<% end %>
</div>

app/views/restaurants/new.html.erb
<h2>New Restaurant</h2>
  <%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, :collection => %w[chinese italian japanese french belgian] %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<div class="header d-flex justify-content-between align-items-center">
  <div class="title">
    <h1><%= @restaurant.name %></h1>
  </div>
  <div>
    <%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant), class: "btn btn-secondary" %>
  </div>
</div>
  <div class="details">
    <h3><%= @restaurant.category.to_s.capitalize! %></h3>
    <address>Address: <%= @restaurant.address %></address>
    <p>Phone: <%= @restaurant.phone_number %></p>
    <br>
    <p><strong>Reviews</strong></p>
    <ul class="list-group">
      <% @restaurant.reviews.each do |review| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <%= review.rating %> - <%= review.content %>
          <%= link_to "Delete", review_path(review), class: "btn btn-sm btn-outline-danger ms-2",
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
          %>
          </li>
        <% end %>
    </ul>
    <br>
    <p><strong>Add a review</strong></p>
    <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, :collection => (1..5) %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
    <% end %>
    <%#= link_to "Add a review",  new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, :collection => (1..5) %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
<%#= f.input :category, :collection => %w[chinese italian japanese french belgian] %>